//Autumn
import autumnrasm1 from "../public/Img/Img/autumn1.jpg";
import autumnrasm2 from "../public/Img/Img/autumn1.jpg";
import autumnrasm3 from "../public/Img/Img/autumn1.jpg";
import autumnrasm4 from "../public/Img/Img/autumn1.jpg";
import autumnrasm5 from "../public/Img/Img/autumn1.jpg";
import autumnrasm6 from "../public/Img/Img/autumn1.jpg";
import autumnrasm7 from "../public/Img/Img/autumn1.jpg";
import autumnrasm8 from "../public/Img/Img/autumn1.jpg";
import autumnrasm9 from "../public/Img/Img/autumn1.jpg";
import autumnrasm10 from "../public/Img/Img/autumn1.jpg";



//Summer
import summerrasm1 from "../public/Img/Img/summer1.jpg";
import summerrasm2 from "../public/Img/Img/summer2.jpg";
import summerrasm3 from "../public/Img/Img/summer3.jpg";
import summerrasm4 from "../public/Img/Img/summer4.jpg";
import summerrasm5 from "../public/Img/Img/summer5.jpg";
import summerrasm6 from "../public/Img/Img/summer6.jpg";
import summerrasm7 from "../public/Img/Img/summer7.jpg";
import summerrasm8 from "../public/Img/Img/summer8.jpg";
import summerrasm9 from "../public/Img/Img/summer9.jpg";

//winter
import rasm1 from "../public/Img/Img/winter1.jpg";
import rasm2 from "../public/Img/Img/winter2.jpg";
import rasm3 from "../public/Img/Img/winter3.jpg";
import rasm4 from "../public/Img/Img/winter4.jpg";
import rasm5 from "../public/Img/Img/winter5.jpg";
import rasm6 from "../public/Img/Img/winter6.jpg";
import rasm7 from "../public/Img/Img/winter7.jpg";
import rasm8 from "../public/Img/Img/winter8.jpg";
import rasm9 from "../public/Img/Img/winter9.jpg";


const data = [
  {
    id: 1,
    name: autumnrasm1,
    img: safari,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Squares",
    category: "Autumn collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 2,
    name: "Multicolored amethyst",
    img: autumnrasm2,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Ikat bedding set",
    category: "Autumn collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 3,
    name: "Stucco ornament",
    img: autumnrasm3,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Circles",
    category: "Autumn collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 4,
    name: "Emerald (AB)",
    img: autumnrasm4,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Emerald (AB)",
    category: "Autumn collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 5,
    name: "Malachite",
    img: autumnrasm5,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Malachite",
    category: "Autumn collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 6,
    name: "spring",
    img: autumnrasm6,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "spring bedding set",
    category: "Autumn collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 7,
    name: "Autumn leaf fall",
    img: autumnrasm7,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Autumn leaf fall (AB)",
    category: "Autumn collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 8,
    name: "Blue Breeze (AB)",
    img: autumnrasm8,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bed linen set Blue Breeze (AB)",
    category: "Autumn collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 9,
    name: "Feather Marquis",
    img: autumnrasm9,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Feather Marquis",
    category: "Autumn collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 10,
    name: "Lavender Plaid",
    img: autumnrasm10,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Lavender Plaid",
    category: "Autumn collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },

  {
    id: 11,
    name: "Vintage style",
    img: summerrasm1,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Squares",
    category: "Summer collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 12,
    name: "fluttering dandelion",
    img: summerrasm2,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Ikat bedding set",
    category: "Summer collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 13,
    name: " French Riviera ",
    img: summerrasm3,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Circles",
    category: "Summer collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 14,
    name: "Dolly the Sheep",
    img: summerrasm4,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Emerald (AB)",
    category: "Summer collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 15,
    name: "Alpine herbs",
    img: summerrasm5,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Malachite",
    category: "Summer collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 16,
    name: "Inspirational",
    img: summerrasm6,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "spring bedding set",
    category: "Summer collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 17,
    name: "Green lotus",
    img: summerrasm7,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Autumn leaf fall (AB)",
    category: "Summer collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 18,
    name: "Mountain cornflower",
    img: summerrasm8,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bed linen set Blue Breeze (AB)",
    category: "Summer collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 19,
    name: "Sakura branch",
    img: summerrasm9,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Feather sakura",
    category: "Summer collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 20,
    name: "Olive  branch",
    img: summerrasm4 ,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Lavender Plaid",
    category: "Summer collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },

  {
    id: 21,
    name: "Squares",
    img: rasm1,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Squares",
    category: "Winter collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 22,
    name: "Ikat",
    img: rasm2,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Ikat bedding set",
    category: "Winter collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 23,
    name: "Circle",
    img: rasm3,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Circles",
    category: "Winter collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 24,
    name: "Geometry blue",
    img: rasm4,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Geometry blue",
    category: "Winter collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 25,
    name: "Tropical leaves",
    img: rasm5,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Tropical leaves",
    category: "Winter collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 26,
    name: "Bambi",
    img: rasm6,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bambi bedding set",
    category: "Winter collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 27,
    name: "Bzyantyum",
    img: rasm7,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Byzantium",
    category: "Winter collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 28,
    name: "Evening garden",
    img: rasm8,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bed linen set Evening garden",
    category: "Winter collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 29,
    name: "Feather marquis",
    img: rasm9,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Feather Marquis",
    category: "Winter collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
  {
    id: 30,
    name: "Lavender roses",
    img: rasm3,
    text: "Bed linen is a household item and bedroom decor designed for comfort and beauty. You can choose from a variety of bed sets that include sheets, blankets, pillow crafts and other accessories. They have various designs, prints, embroideries or other design elements. They are easy and quick to clean and clean. They are made from soft materials and they make your bedrooms cozy and cozy.",
    title: "Bedding set Lavender roses",
    category: "Winter collection",
    Material: "100% cotton flannel",
    Pillowcase: "50x70 cm (2 pcs.)",
    sheet: "Bed sheet:",
    Duvet: "Duvet cover",
    Size: "Special size",
    Manufacturer: "Bukhara Natural Product",
  },
];

export default data;
